version: '2'

services:
  proxy:
    build: proxy/
    depends_on:
      - crowi
      - owncloud
    links:
      - crowi
      - owncloud
    ports:
      - 80:80
      - 443:443
  crowi:
    image: bakudankun/crowi:latest
    links:
      - crowi-mongo:db
      - crowi-redis:redis
      - crowi-elasticsearch:es
    ports:
      - 5000:3000
    volumes:
      - "~/szm-dev/wiki:/data"
    environment:
      FILE_UPLOAD: local

  crowi-mongo:
    image: mongo
    volumes:
      - "~/szm-dev/wiki-mongo:/data/db"
  crowi-redis:
    image: redis:alpine

  crowi-elasticsearch:
    image: elasticsearch:2
    # プラグインのKuromojiが必要
    entrypoint:
      - bash
      - -c
      - >-
        bin/plugin list | grep -q analysis-kuromoji
        || bin/plugin install analysis-kuromoji
        && exec /docker-entrypoint.sh $$0 $$@
    command: elasticsearch
  owncloud:
    image: owncloud
    depends_on:
      - db-owncloud
    links:
      - db-owncloud:db
    ports:
      - 5001:80
    volumes:
      - ~/szm-dev/owncloud:/var/www/html
  db-owncloud:
    image: sizuma/mysql-jp:5.6
    environment:
      MYSQL_DATABASE: owncloud
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ~/szm-dev/owncloud-db:/var/lib/mysql
